<!--شروع جدیدترین محصولات-->
<section class="lasts right">
<div class="title rt"><h4 class="rt">محصولات <div>جدید</div></h4><h5 class="rt rt-15">تازه ترین محصولات وب استور</h5></div>

<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="0" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini2.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini3.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini4.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini5.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini6.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini7.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini8.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini9.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini10.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini11.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini12.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini13.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini14.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="0" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini15.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini16.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini17.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini18.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini19.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini20.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini21.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini22.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini23.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini24.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini25.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini26.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini27.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini28.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini29.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini30.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini31.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini32.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini33.png" width="80px" height="80px"></a></div>

<div class="des rt rt-14">
<h3>جدیدترین قالب‌ها و افزونه‌های وب استور</h3>
<p>آخرین محصولات وب استور که در بالا می‌بینید، شامل قالب‌های دستچین شده توسط مدیران وب استور است و اگر نیاز شما را برطرف نکرد،<br> پیشنهاد می‌کنیم حتماً از دسته‌بندی‌های قالب‌های آماده ما، اعم از قالب وردپرس، جوملا، WHMCS و... دیدن نمایید.</p>
<p>حتماً قالب زیبایی برای طراحی سایت خود پیدا خواهید کرد.</p>
<div class="btns rt-13">
<a href="category.html">آخرین محصولات</a>
<a href="category.html">محصولات پرطرفدار</a>
</div>
</div>

</section>
<!--پایان جدیدترین محصولات-->