<!--شروع آخرین های دسته بندی های مختلف-->
<section class="boxs right">

<!--شروع جدیدترین پوسته های وردپرس-->
<aside class="box right big">
<div class="title rt"><i class="fa fa-wordpress right"></i><h4 class="right rt-17">پوسته های <div>وردپرس</div></h4><span class="left rt-13">قالب های وردپرس</span></div>
<div class="entery rt">
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="0" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini14.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini15.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini16.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini17.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini18.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini19.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini20.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini21.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini22.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini23.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini24.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini25.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini26.png" width="80px" height="80px"></a></div>
<div class="wr-item"><a target="_blank" href="product.html" class="screenshot-preview" data-preview="images/test.jpg" data-titr="تیتر در این مکان" data-titrsmall="قالب PSD / لایه باز شرکتی" data-price="۶۰,۰۰۰" title="عنوان در این جا"><img src="<?php echo MR_TDU ?>/images//mini27.png" width="80px" height="80px"></a></div>
</div>
</aside>
<!--پایان جدیدترین پوسته های وردپرس-->
